* Error messages.

#define ccERR_TABLE_NOT_OPEN    '<Insert1> is not open.'
#define ccERR_TABLE_NOT_FOUND   '<Insert1> was not found in the database.'
#define ccERR_NO_EXTENSIONS     'The Stonefield extensions defined for <Insert1> are incomplete - <Insert2>.'
#define ccERR_NO_TABLE_SELECTED 'No table was specified.'
#define ccERR_TABLE_IN_DBC      '<Insert1> is already in the database.'
#define ccERR_TABLE_IN_META     '<Insert1> is already in the meta data.'
#define ccERR_INVALID_PROPERTY  '<Insert1> is not a valid database field.'
#define ccERR_FILE_EXISTS       '<Insert1> already exists.'
#define ccERR_INDEX_EXISTS      'There is already an index with that name.'
#define ccERR_FIELD_EXISTS      'There is already a field with that name.'
#define ccERR_FILE_IN_USE		'File is in use.'
#define ccERR_TOO_MANY_FILES	'Too many files open.'
#define ccERR_TAG_NOT_FOUND     'Tag <Insert1> was not found.'
#define ccERR_NO_TABLES         'There are no tables to process.'
#define ccERR_CANT_OPEN_EXCL    '<Insert1> cannot be opened exclusively.'
#define ccERR_NOT_OPEN_EXCL     '<Insert1> must be opened exclusively.'
#define ccERR_OUT_OF_MEMORY     'Insufficient memory.'
#define ccERR_INDEX_INVALID     'Tag <Insert1> is invalid.'
#define ccERR_IDX_EXPR_INVALID  'The index expression is invalid.'
#define ccERR_FILTER_TOO_LONG   'The filter expression is too long.'
#define ccERR_CANT_REINDEX      '<Insert1> could not be reindexed - <Insert2>.'
#define ccERR_DBC_NOT_OPEN      'The database is not open as a table.'
#define ccERR_NO_PHDBASE        'PHDBASE is needed to create index <Insert1> of <Insert2> but it could not be loaded.'
#define ccERR_BELONG_ANOTHER    'This table belongs to another database.'
#define ccERR_INVALID_DBCXPROPS 'Invalid property cursor name.'
#define ccERR_CANT_UPDATE_ID    'Unable to update the last used row ID.'
#define ccERR_CANT_ADD_META     'You are not allowed to add a meta data table to the <Insert1>.'
#define ccERR_INVALID_DEMO      'The demo version of Stonefield Database Toolkit can only be used with the sample database.'
#define ccERR_INVALID_COLLATE   'This code page does not support the <Insert1> collate sequence used for tag <Insert2>.'
#define ccERR_NOT_UPDATED       'There was a problem updating this table. Its structure was not changed.'
#define ccERR_VCX_NOT_EXIST     'The class library selected for field <Insert1> (<Insert2>) does not exist.'
#define ccERR_CANT_SAVE_PREF    'There is a problem saving properties.'
#define ccERR_CANT_DEF_PREF     'There is a problem registering default properties.'
#define ccERR_CANT_EDIT_PROP    'The SDT meta data table cannot be opened exclusively, so you cannot add, edit, or remove extended properties at this time.'
#define ccERR_NO_TABLES_IN_DIR  'There are no tables in that directory.'
#define ccERR_WORD_NOT_FOUND    'Microsoft Word could not be found.'
#define ccERR_WORD_DOC_OPEN     'Another document with this name is already open in Word.'
#define ccERR_WORD_BUSY         'Word appears to be busy doing something else right now.'
#define ccERR_WORD_NO_BOOKMARK  'The template for this report has been modified such that the expected bookmark no longer exists.'
#define ccERR_WORD_NOT_STARTED  'Microsoft Word could not be started.'
#define ccERR_WORD_UNKNOWN_NAME 'There is a problem in the VBA commands sent to Word.'
#define ccERR_WORD_CLOSED       'Word was closed so it will be restarted.'
#define ccERR_BAD_FIELD_REP_DIR 'The Field Repository directory defined in the SDT Properties form conflicts with the meta data for the current database. Please edit this property in SDT Properties.'
#define ccERR_NO_FIELD_REP_DIR  'The Field Repository directory is not defined. Please edit this property in SDT Properties.'
#define ccERR_ALIAS_IN_USE      'There is already a cursor with that alias in use.'
#define ccERR_INVALID_FILENAME  'Please enter a valid filename.'
#define ccERR_MUST_REDEFINE     'View <Insert1> must be redefined. To do this, select the view in the SDT Database Explorer and click on the Redefine button.'
#define ccERR_INVALID_VIEW      'View <Insert1> is invalid: <Insert2>'
#define ccERR_COPY_PROP_LEN     '<Insert1> cannot be copied: one of its properties exceeds 254 characters'
#define ccERR_CANT_PROCESS_FREE 'This method cannot be used for free tables.'
#define ccERR_INVALID_FIELD     '<Insert1> is not a valid field name.'
	* new in SDT 6.0c
#define ccERR_REQUEST_CANCELED  'Request was canceled.'
	* new in SDT 6.1

* Display messages.

#define ccMSG_TITLE             'Stonefield Database Explorer'
#define ccMSG_READONLY          '[Read Only]'
#define ccMSG_CREATING          'Creating <Insert1>...'
#define ccMSG_UPDATING          'Updating <Insert1>...'
#define ccMSG_REMOVING          'Removing <Insert1>...'
#define ccMSG_COPYING           'Copying <Insert1>...'
#define ccMSG_MOVING            'Moving <Insert1>...'
#define ccMSG_PACKING           'Packing <Insert1>...'
#define ccMSG_REINDEXING        'Reindexing <Insert1>...'
#define ccMSG_REPAIRING         'Repairing <Insert1>...'
#define ccMSG_PROCESSING        'Processing <Insert1>...'
#define ccMSG_CHECKING          'Checking <Insert1>...'
#define ccMSG_REDEFINING        'Redefining view <Insert1>...'
#define ccMSG_UPDATING_LINKED   'Updating linked fields...'
#define ccMSG_OPEN_DATABASE     'Database:'
#define ccMSG_COPYRIGHT         '(c) 1996-2010 Stonefield Systems Group Inc.'
#define ccMSG_RETR_EXT_PROP     'Retrieving extended properties...'
#define ccMSG_UPD_EXT_PROP      'Updating extended properties...'
#define ccMSG_UPDATING_META     'Updating meta data table structures...'
#define ccMSG_OPENING           'Opening <Insert1>...'
#define ccMSG_RECORDS_TOTAL     '<Insert1>   records total'
#define ccMSG_DOING_INDEX       'Index <Insert1> of <Insert2>'
#define ccMSG_RENAME_EDITS      'The following objects must be edited since their properties refer to the former name of <Insert1> (<Insert2>):'
#define ccMSG_REMOVE_EDITS      'The following objects must be edited since their properties refer to <Insert1>:'
#define ccMSG_RENAME_FIELD      'Renaming field...'
#define ccMSG_REPAIR            'Repair'
#define ccMSG_REINDEX           'Reindex'
#define ccMSG_PROGRESS          'Progress'
#define ccMSG_LOCATE            '<Insert1>:'
#define ccMSG_OPEN              'Open'
#define ccMSG_PLEASE_WAIT       'Please wait...'
#define ccMSG_PRINTING          'Printing documentation...'
#define ccMSG_DIRECTORY         'Select directory'
#define ccMSG_READING_DBC       'Reading database objects...'
#define ccMSG_UPDATING_VIEW     'Updating view field properties...'
#define ccMSG_ERR_ON_CLIPBOARD  'The error message has been put on the Clipboard.'
#define ccMSG_COPY_TABLE_FROM   'Copy <Insert1> To'

* Captions and labels.

#define ccFRM_SDT_CAPTION       'Stonefield Database Explorer'
#define ccFRM_TD_CAPTION        'Stonefield Extended Table Designer - '
#define ccFRM_PROPS_CAPTION     'Other <Insert1> Properties'
#define ccFRM_PREF_CAPTION      'Stonefield Database Explorer Properties'
#define ccFRM_SYSDOC_CAPTION    'Database Documentation'
#define ccFRM_IDXWIZ_CAPTION    'Index Wizard'
#define ccFRM_NOTIFY_CAPTION    'Note'
#define ccFRM_SELDBC_CAPTION    'Select Database'
#define ccFRM_NEW_PROP_CAPTION  'New Property'
#define ccFRM_EDIT_PROP_CAPTION 'Edit Property'
#define ccFRM_TD_RECORDS        'Records:  <Insert1>'
#define ccFRM_TD_FIELDS         'Fields:  <Insert1>'
#define ccFRM_TD_LENGTH         'Length:  <Insert1>'
#define ccFRM_SORT_ORDER        'Sort Order'
#define ccFRM_TD_DEF_CLASS      '<Default>'
#define ccFRM_NEW_VIEW_CAPTION  'New View'
	* new in SDT 6.0
#define ccCAP_MODIFY            'Modify <Insert1>'
	* new in SDT 6.0
#define ccCAP_BROWSE            'Browse <Insert1>'
	* new in SDT 6.0
#define ccCAP_COPY              'Copy <Insert1>'
	* new in SDT 6.0
#define ccCAP_CREATE            'Create new <Insert1>'
	* new in SDT 6.0
#define ccCAP_ADD               'Add <Insert1>'
	* new in SDT 6.0
#define ccCAP_ADD_TO_META_DATA  'Add <Insert1> to meta data'
	* new in SDT 6.0
#define ccCAP_ADD_TO_DBC        'Add <Insert1> to database'
	* new in SDT 6.0
#define ccCAP_BATCHADD_META     'Batch add <Insert1> to meta data'
	* new in SDT 6.0
#define ccCAP_BATCHADD_DBC      'Batch add <Insert1> to database'
	* new in SDT 6.0
#define ccCAP_REMOVE_META_DATA  'Remove <Insert1> from meta data'
	* new in SDT 6.0
#define ccCAP_REMOVE_DBC        'Remove <Insert1> from database'
	* new in SDT 6.0
#define ccCAP_REDEFINE_VIEW     'Redefine view'
	* new in SDT 6.0
#define ccCAP_REDEFINE_ALL_VIEWS 'Redefine all views in database'
	* new in SDT 6.0

* Questions.

#define ccQST_REMOVE_TABLE      'Remove <Insert1> and any views or relations based on it from the database?'
#define ccQST_REMOVE_FREE_TABLE 'Remove <Insert1> from the meta data?'
#define ccQST_NOT_EXCLUSIVE     '<Insert1> could not be opened exclusively. Would you like to view it in read-only mode?'
#define ccQST_NO_EXTENSIONS     'There are no Stonefield extensions defined for <Insert1>. Do you want to create them?'
#define ccQST_REMOVE_REL_INDEX  'The <Insert1> index is involved in one or more relations, and removing it will also remove those relations. Are you sure you want to remove it?'
#define ccQST_REMOVE_INDEX      'Remove index <Insert1>?'
#define ccQST_REMOVE_FIELD      'Remove field <Insert1>?'
#define ccQST_REMOVE_EXT_PROP   'Remove this extended property?'
#define ccQST_REMOVE_IDX_FIELD  'The <Insert1> field is involved in one or more indexes. Removing it will also remove those indexes and any relations based on those indexes. Are you sure you want to remove it?'
#define ccQST_EXIT_NO_SAVE      'Exit without saving your changes?'
#define ccQST_MOVE_TABLE        'Moving <Insert1> will cause any views or relations based on it to be removed. Do you wish to continue?'
#define ccQST_VALIDATE          'Validating the meta data can take quite a while. Are you sure you want to proceed?'
#define ccQST_REDEFINE_VIEW     'View <Insert1> must be redefined. Would you like to do that now?'
#define ccQST_ADJUST_VIEW       'Would you like the table references in this view to be adjusted so they reference tables in this database (Yes) or left alone so they reference tables in the original database (No)?'
#define ccQST_NO_META_DATA      'There are no meta data tables in the chosen directory. Would you like to create them (Yes), remove the directory from the registered list (No), or do nothing (Cancel)?'
	* new in SDT 6.0c

* Report constants.

#define ccREP_TOT_SIZE          'Total record size:'
#define ccREP_SYSTEM            'System:'
#define ccREP_DATABASE          'Database:'
#define ccREP_TABLE             'Table:'
#define ccREP_PATH              'Path:'
#define ccREP_CAPTION           'Caption:'
#define ccREP_COMMENTS          'Comments:'
#define ccREP_VALID_RULE        'Validation Rule:'
#define ccREP_VALID_TEXT        'Validation Text:'
#define ccREP_INS_TRIGGER       'Insert Trigger:'
#define ccREP_UPD_TRIGGER       'Update Trigger:'
#define ccREP_DEL_TRIGGER       'Delete Trigger:'
#define ccREP_PRIMARY_KEY       'Primary Key:'
#define ccREP_CODEPAGE          'Code Page:'
#define ccREP_BATCHUPDATECOUNT  'BatchUpdateCount:'
#define ccREP_COMPAREMEMO       'CompareMemo:'
#define ccREP_CONNECTNAME       'ConnectName:'
#define ccREP_FETCHASNEEDED     'FetchAsNeeded:'
#define ccREP_FETCHMEMO         'FetchMemo:'
#define ccREP_FETCHSIZE         'FetchSize:'
#define ccREP_MAXRECORDS        'MaxRecords:'
#define ccREP_OFFLINE           'Offline:'
#define ccREP_PARAMETERLIST     'ParameterList:'
#define ccREP_PREPARED          'Prepared:'
#define ccREP_SENDUPDATES       'SendUpdates:'
#define ccREP_SHARECONNECTION   'ShareConnection:'
#define ccREP_SQL               'SQL:'
#define ccREP_TABLES            'Tables:'
#define ccREP_UPDATETYPE        'UpdateType:'
#define ccREP_UPDATE            'Update'
#define ccREP_DELETETHENINSERT  'Delete then Insert'
#define ccREP_USEMEMOSIZE       'UseMemoSize:'
#define ccREP_WHERETYPE         'WhereType:'
#define ccREP_KEYFIELDSONLY     'Key fields only'
#define ccREP_KEYANDUPDATABLE   'Key and updatable fields'
#define ccREP_KEYANDMODIFIED    'Key and modified fields'
#define ccREP_KEYANDTIMESTAMP   'Key and timestamp fields'
#define ccREP_INPUTMASK         'Input Mask:'
#define ccREP_FORMAT            'Format:'
#define ccREP_DEFAULT           'Default:'
#define ccREP_DISPLAYCLASS      'Display Class:'
#define ccREP_CLASSLIBRARY      'Class Library:'
#define ccREP_EXPRESSION        'Expression:'
#define ccREP_FILTER            'Filter:'
#define ccREP_COLLATE           'Collate:'
#define ccREP_VIEWTYPE          'View type:'
#define ccREP_KEYFLD            'Key field:'
#define ccREP_UPDATABLE         'Updatable:'
#define ccREP_UPDATENAME        'Update name:'
#define ccREP_CALCULATION       'Calculation:'

* Miscellaneous constants.

#define ccMENU_BAR_PROMPT_SDT   iif(version(5) >= 800, 'Stone\<field Database Explorer', 'Stonefield Database E\<xplorer')
	* Prompt for the pad in the menu bar
#define ccMENU_BAR_PROMPT_PREF  'SDT Prop\<erties...'
	* Prompt for the Properties pad in the menu bar
#define ccALL                   'ALL'
	* "ALL" passed to Reindex or Update
#define ccUNTITLED              'Untitled'
	* string returned by GETFILE() when New is selected
#define ccDELETED_TAG_COMMENT   'This tag improves Rushmore performance.'
#define ccMETA_TABLE            'meta table'
#define ccLOCAL                 'Local'
#define ccREMOTE                'Remote'
#define ccUNKNOWN               'Unknown'

* Other prompts.

#define ccMETA_DATA             'meta data'
	* new in SDT 6.0
#define ccTABLES_PROPER         'Tables'
#define ccDATABASE_PROPER       'Database'
#define ccDATABASE_LOWER        'database'
	* new in SDT 6.0
#define ccDATABASES             'Databases'
#define ccDATABASES_LOWER       'databases'
	* new in SDT 6.0
#define ccLOADING               'Loading...'
#define ccTABLES                'tables'
#define ccTABLE                 'Table'
#define ccTABLE_LOWER           'table'
	* new in SDT 6.0
#define ccVIEW                  'View'
#define ccVIEWS_PROPER          'Views'
#define ccVIEW_LOWER            'view'
	* new in SDT 6.0
#define ccTABLE_OR_VIEW         'table or view'
	* new in SDT 6.0
#define ccINDEXES               'indexes'
#define ccFIELD_PROPER          'Field'
#define ccUSER_PROPER           'User-Defined'
#define ccINDEX_PROPER          'Index'
#define ccRELATIONS             'relations'
#define ccDATABASE              'database'
#define ccTHIS_TABLE            'this table'
#define ccRENAMED_FIELDS        'the following field(s)'
#define ccPACK                  'Pack'
#define ccALL_TABLES            'All Tables'
#define ccCANCEL                'Cancel'
#define ccDEBUG                 'Debug'
#define ccCONTINUE				'Continue'
#define ccSELECT                'Select'
#define ccLIBRARY               'Field Repository'
#define ccFREE_TABLES           'Free Tables'
#define ccFREE_TABLE            'Free Table'
#define ccFREE_TABLE_LOWER      'free table'
	* new in SDT 6.0
#define ccFREE_TABLES_LOWER     'free tables'
	* new in SDT 6.0
#define ccBROWSE                'Browse'
#define ccLIST                  'List'
#define ccYES                   'Yes'
#define ccNO                    'No'
#define ccOBJECT                'object'
#define ccOBJECTS               'objects'

* Error message strings (besides those found in DBCXMGR.H).

#define ccMSG_CODE              'Code:'
#define ccMSG_OBJECT            'Object:'
